item {
  id: 1
  name: 'Chimpanzee'
}

item {
  id: 2
  name: 'Gelada'
}

item {
  id: 3
  name: 'Gorilla'
}

item {
  id: 4
  name: 'Mandrill'
}

item {
  id: 5
  name: 'Pygmy Marmoset'
}

item {
  id: 6
  name: 'Orangutan'
}

item {
  id: 7
  name: 'Golden Snub-nosed'
}

